services:
  - type: web
    name: luxe-hair-collection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: luxe-hair-db
          property: connectionString
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SHOP_URL
        sync: false
      - key: NEBIUS_API_KEY
        sync: false
      - key: NEBIUS_API_URL
        value: "https://api.nebius.ai/v1"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_APP
        value: "app.py"
      - key: NEBIUS_EMBEDDINGS_MODEL
        value: "text-embedding-3-small"
      - key: NEBIUS_CHAT_MODEL
        value: "llama-3-8b-instruct"
      - key: NEBIUS_IMAGE_MODEL
        value: "stability-ai/stable-diffusion-xl-refiner-1.0"

databases:
  - name: luxe-hair-db
    plan: free
    databaseName: luxe_hair
    user: luxe_hair
