services:
  - type: web
    name: luxe-hair-collection
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_NEBIUS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_NEBIUS_API_URL
        value: https://api.studio.nebius.com/v1/
      - key: DATABASE_URL
        fromDatabase:
          name: luxe-hair-db
          property: connectionString
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: luxe-hair-collection
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health

databases:
  - name: luxe-hair-db
    plan: starter
    databaseName: luxe_hair_production
    user: luxe_hair
